/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace InviteMeFactory {
  export type EventInfoStruct = {
    contractAddress: AddressLike;
    eventId: BigNumberish;
    host: AddressLike;
    name: string;
    date: BigNumberish;
    isActive: boolean;
  };

  export type EventInfoStructOutput = [
    contractAddress: string,
    eventId: bigint,
    host: string,
    name: string,
    date: bigint,
    isActive: boolean
  ] & {
    contractAddress: string;
    eventId: bigint;
    host: string;
    name: string;
    date: bigint;
    isActive: boolean;
  };
}

export interface InviteMeFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "activeContract"
      | "allEvents"
      | "createEventSingle"
      | "deployNewContract"
      | "enableSingleContractMode"
      | "getActiveContract"
      | "getAllEvents"
      | "getEventCount"
      | "getHostEvents"
      | "hostEventIndices"
      | "mintInviteSingle"
      | "owner"
      | "renounceOwnership"
      | "transferOwnership"
      | "useSingleContract"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ContractDeployed"
      | "EventCreated"
      | "OwnershipTransferred"
      | "SingleContractModeEnabled"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "activeContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "allEvents",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createEventSingle",
    values: [string, BigNumberish, string, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "deployNewContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "enableSingleContractMode",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAllEvents",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEventCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getHostEvents",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hostEventIndices",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "mintInviteSingle",
    values: [BigNumberish, AddressLike, string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "useSingleContract",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "activeContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "allEvents", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createEventSingle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployNewContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "enableSingleContractMode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllEvents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEventCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getHostEvents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hostEventIndices",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintInviteSingle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "useSingleContract",
    data: BytesLike
  ): Result;
}

export namespace ContractDeployedEvent {
  export type InputTuple = [
    contractAddress: AddressLike,
    deployer: AddressLike
  ];
  export type OutputTuple = [contractAddress: string, deployer: string];
  export interface OutputObject {
    contractAddress: string;
    deployer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EventCreatedEvent {
  export type InputTuple = [
    eventId: BigNumberish,
    host: AddressLike,
    name: string,
    date: BigNumberish
  ];
  export type OutputTuple = [
    eventId: bigint,
    host: string,
    name: string,
    date: bigint
  ];
  export interface OutputObject {
    eventId: bigint;
    host: string;
    name: string;
    date: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SingleContractModeEnabledEvent {
  export type InputTuple = [contractAddress: AddressLike];
  export type OutputTuple = [contractAddress: string];
  export interface OutputObject {
    contractAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface InviteMeFactory extends BaseContract {
  connect(runner?: ContractRunner | null): InviteMeFactory;
  waitForDeployment(): Promise<this>;

  interface: InviteMeFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  activeContract: TypedContractMethod<[], [string], "view">;

  allEvents: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, string, bigint, boolean] & {
        contractAddress: string;
        eventId: bigint;
        host: string;
        name: string;
        date: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  createEventSingle: TypedContractMethod<
    [
      _name: string,
      _date: BigNumberish,
      _location: string,
      _maxCapacity: BigNumberish,
      _isPrivate: boolean
    ],
    [bigint],
    "nonpayable"
  >;

  deployNewContract: TypedContractMethod<[], [string], "nonpayable">;

  enableSingleContractMode: TypedContractMethod<[], [void], "nonpayable">;

  getActiveContract: TypedContractMethod<[], [string], "view">;

  getAllEvents: TypedContractMethod<
    [],
    [InviteMeFactory.EventInfoStructOutput[]],
    "view"
  >;

  getEventCount: TypedContractMethod<[], [bigint], "view">;

  getHostEvents: TypedContractMethod<
    [_host: AddressLike],
    [InviteMeFactory.EventInfoStructOutput[]],
    "view"
  >;

  hostEventIndices: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  mintInviteSingle: TypedContractMethod<
    [_eventId: BigNumberish, _guest: AddressLike, _metadataURI: string],
    [bigint],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  useSingleContract: TypedContractMethod<[], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "activeContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "allEvents"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, string, bigint, boolean] & {
        contractAddress: string;
        eventId: bigint;
        host: string;
        name: string;
        date: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "createEventSingle"
  ): TypedContractMethod<
    [
      _name: string,
      _date: BigNumberish,
      _location: string,
      _maxCapacity: BigNumberish,
      _isPrivate: boolean
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deployNewContract"
  ): TypedContractMethod<[], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "enableSingleContractMode"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getActiveContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getAllEvents"
  ): TypedContractMethod<[], [InviteMeFactory.EventInfoStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getEventCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getHostEvents"
  ): TypedContractMethod<
    [_host: AddressLike],
    [InviteMeFactory.EventInfoStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "hostEventIndices"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "mintInviteSingle"
  ): TypedContractMethod<
    [_eventId: BigNumberish, _guest: AddressLike, _metadataURI: string],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "useSingleContract"
  ): TypedContractMethod<[], [boolean], "view">;

  getEvent(
    key: "ContractDeployed"
  ): TypedContractEvent<
    ContractDeployedEvent.InputTuple,
    ContractDeployedEvent.OutputTuple,
    ContractDeployedEvent.OutputObject
  >;
  getEvent(
    key: "EventCreated"
  ): TypedContractEvent<
    EventCreatedEvent.InputTuple,
    EventCreatedEvent.OutputTuple,
    EventCreatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "SingleContractModeEnabled"
  ): TypedContractEvent<
    SingleContractModeEnabledEvent.InputTuple,
    SingleContractModeEnabledEvent.OutputTuple,
    SingleContractModeEnabledEvent.OutputObject
  >;

  filters: {
    "ContractDeployed(address,address)": TypedContractEvent<
      ContractDeployedEvent.InputTuple,
      ContractDeployedEvent.OutputTuple,
      ContractDeployedEvent.OutputObject
    >;
    ContractDeployed: TypedContractEvent<
      ContractDeployedEvent.InputTuple,
      ContractDeployedEvent.OutputTuple,
      ContractDeployedEvent.OutputObject
    >;

    "EventCreated(uint256,address,string,uint256)": TypedContractEvent<
      EventCreatedEvent.InputTuple,
      EventCreatedEvent.OutputTuple,
      EventCreatedEvent.OutputObject
    >;
    EventCreated: TypedContractEvent<
      EventCreatedEvent.InputTuple,
      EventCreatedEvent.OutputTuple,
      EventCreatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "SingleContractModeEnabled(address)": TypedContractEvent<
      SingleContractModeEnabledEvent.InputTuple,
      SingleContractModeEnabledEvent.OutputTuple,
      SingleContractModeEnabledEvent.OutputObject
    >;
    SingleContractModeEnabled: TypedContractEvent<
      SingleContractModeEnabledEvent.InputTuple,
      SingleContractModeEnabledEvent.OutputTuple,
      SingleContractModeEnabledEvent.OutputObject
    >;
  };
}
